apiVersion: apps/v1
kind: Deployment
metadata:
  name: toys-deployment
  labels:
    app: toys
spec:
  replicas: 1
  selector:
    matchLabels:
      app: toys
  template:
    metadata:
      labels:
        app: toys
    spec:
      containers:
      - name: toys
        image: 571162942984.dkr.ecr.us-east-1.amazonaws.com/shopping-site-toys:c8ef343dc8a69d620821d43257cda0190c3e47c3
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: toys-service
  labels:
    app: toys
spec:
  type: ClusterIP
  selector:
    app: toys
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
